###
GET http://localhost:3001/api/persons
###
DELETE http://localhost:3001/api/persons/2584
###
POST http://localhost:3001/api/persons
content-type: application/json 

{
    "name": "Yepeto Hellas1",
    "number": "666-666666"
}